export type Topic = { id:string; area:string; name:string; weight:number; frequency:number };
export type Question = { id:number; area:string; topic:string; difficulty:string; prompt:string; options:string[]; answer:number; explanation:string; wrong:string[]; sourceNote?:string };
export const exam={date:"2026-08-30",dateLabel:"30 de agosto de 2026",totalQuestions:50,durationMinutes:240,startTime:"14h",endTime:"18h",minimumScore:70,distribution:[["Língua Portuguesa",10,2],["Fundamentos da Educação, transversais e legislação",10,1],["Tecnologia Aplicada à Educação",10,1],["Conhecimentos Específicos de Informática",20,3]] as [string,number,number][],rules:"50 questões, cinco alternativas e uma correta; 4 horas, das 14h às 18h. Portões das 12h30 às 13h45. Saída após 2h30 e caderno após 3h30. Nota mínima: 70/100.",bibliography:"O edital atual não apresenta bibliografia oficial. A prova de 2023 citou Puga (2009), Cormen (2012), Deitel (2010), Pressman (2016), Guedes (2009), Gamma et al. (2000), Raghu e Gehrke (2011) e documentação MariaDB.",historicalComparison:"Em 2023 eram 60 questões: Português 10, Fundamentos/Legislação 10, Gerais de MT 10, Informática Básica 10 e Específicos 20. Em 2026 são 50: permanecem Português, Fundamentos e Específicos; os dois blocos intermediários dão lugar a Tecnologia Aplicada à Educação (10). O específico permanece essencialmente igual.",historicalStyle:"Em 2023 predominaram afirmações I/II/III, interpretação de código e conceitos com referências. Das 20 específicas, 3 foram anuladas.",historicalFrequency:"Algoritmos/estruturas 5; POO 3; Engenharia de Software 2; Banco de Dados 2; UML 3; GoF 2; Python 1; Java 1; PHP 1. As questões de Java, PHP e uma de POO foram anuladas."};
export const topics:Topic[]=[
 ["alg","Programação","Algoritmos e Lógica de Programação",40,90],["ed","Programação","Estruturas de Dados",40,100],["poo","Programação","Programação Orientada a Objetos",40,60],["es","Engenharia de Software","Definição, processos e gerência de projetos",10,40],
 ["bd1","Banco de Dados","Fundamentos, arquivos e modelo ER",30,80],["bd2","Banco de Dados","Normalização e dependências funcionais",30,92],["bd3","Banco de Dados","Álgebra e cálculo relacional",30,68],["bd4","Banco de Dados","Arquiteturas, modelos lógicos e representação física",30,64],["bd5","Banco de Dados","Organização de arquivos e métodos de acesso",30,61],["bd6","Banco de Dados","DDL, DML, DCL e DTL",30,84],["bd7","Banco de Dados","Apoio à decisão, DW, ETL, OLAP, Data Mining e BI",30,60],["bd8","Banco de Dados","Modelagem, otimização, distribuídos e cluster",30,66],["bd9","Banco de Dados","Segurança, autorização, usuários e perfis",30,62],["bd10","Banco de Dados","Transações, concorrência e recuperação",30,90],["bd11","Banco de Dados","Integridade, backup, restauração e continuidade",30,76],["bd12","Banco de Dados","Processos, documentação e aplicações com BD",30,58],
 ["uml","Modelagem","UML 2.x",20,60],["gof","Modelagem","Padrões de Projeto GoF",20,40],["java","Linguagens","Java",40,20],["python","Linguagens","Python",40,20],["php","Linguagens","PHP",40,20],["port1","Língua Portuguesa","Interpretação, gêneros, sequências e linguagem",20,50],["port2","Língua Portuguesa","Morfologia, sintaxe, semântica e textualidade",20,50],["port3","Língua Portuguesa","Ortografia, pontuação e acentuação",20,50],["edu1","Fundamentos da Educação","Estado, ensino-aprendizagem, currículo, avaliação e gestão",10,50],["edu2","Fundamentos da Educação","CF, LDB, Lei 11.892, Regulamento IFMT e carreira EBTT",10,50],["edu3","Fundamentos da Educação","Lei 8.112, ética, direitos humanos, LGPD, PNE e PROEJA",10,50],["edu4","Fundamentos da Educação","Inclusão, organizações, inovação, ethos público e relações étnico-raciais",10,50],["edu5","Fundamentos da Educação","Aspectos de Mato Grosso e atualidades",10,50],["tec1","Tecnologia Educacional","Computação, Linux, Windows 10 e segurança",10,50],["tec2","Tecnologia Educacional","LibreOffice e Microsoft Office",10,50],["tec3","Tecnologia Educacional","Internet, e-mail, Google Drive e ferramentas Google",10,50],["tec4","Tecnologia Educacional","Classroom, Meet, Moodle, multimeios e TIC",10,50],["tec5","Tecnologia Educacional","Tecnologias digitais, mídias, curadoria e EaD",10,50],["tec6","Tecnologia Educacional","IA, mobile learning, IoT, acessibilidade e prompts",10,50]
].map(([id,area,name,weight,frequency])=>({id,area,name,weight,frequency} as Topic));
export const questions:Question[]=[
 {id:1,area:"Programação",topic:"Algoritmos",difficulty:"Média",prompt:"Considere a busca binária em um vetor ordenado com 1.024 elementos distintos. No pior caso, quantas comparações são necessárias para concluir que um valor não está no vetor?",options:["9","10","11","512","1.024"],answer:2,explanation:"Como 1.024 = 2¹⁰, uma busca malsucedida pode exigir 11 comparações para alcançar o intervalo vazio.",wrong:["Desconsidera passos.","Desconsidera a comparação final.","Correta.","Busca linear parcial.","Busca linear completa."]},
 {id:2,area:"Banco de Dados",topic:"Normalização",difficulty:"Média",prompt:"Uma relação está na 3FN quando está na 2FN e, para toda dependência funcional não trivial X → A, qual condição é suficiente?",options:["X não é superchave","A é chave primária","X é superchave ou A é atributo primo","A não admite NULL","X tem um atributo"],answer:2,explanation:"A 3FN admite que X seja superchave ou que A seja atributo primo.",wrong:["É o oposto.","Não exige chave primária.","Correta.","Nullabilidade não define 3FN.","A cardinalidade não é o critério."]},
 {id:3,area:"Programação",topic:"Python",difficulty:"Fácil",prompt:"Qual é a saída de: valores = [1, 2, 3]; print([x*x for x in valores if x % 2])?",options:["[1, 4, 9]","[1, 9]","[2]","[2, 6]","Erro"],answer:1,explanation:"O filtro mantém 1 e 3; a expressão produz 1 e 9.",wrong:["Ignora o filtro.","Correta.","Confunde filtro e resultado.","Não eleva ao quadrado.","A sintaxe é válida."]},
 {id:4,area:"Modelagem",topic:"Padrões GoF",difficulty:"Média",prompt:"Qual padrão define uma família de algoritmos, encapsula cada um e os torna intercambiáveis em tempo de execução?",options:["Observer","Strategy","Facade","Builder","Singleton"],answer:1,explanation:"Strategy encapsula algoritmos atrás de uma interface comum.",wrong:["Notifica dependentes.","Correta.","Simplifica subsistema.","Constrói objetos.","Controla instanciação."]},
 {id:5,area:"Banco de Dados",topic:"Transações",difficulty:"Difícil",prompt:"I. Leitura suja pode ocorrer em READ UNCOMMITTED. II. SERIALIZABLE impede anomalias de serialização. III. Durabilidade garante isolamento. Assinale a correta.",options:["Somente I","Somente II","I e II","II e III","I, II e III"],answer:2,explanation:"I e II são verdadeiras. Durabilidade é permanência após commit, não isolamento.",wrong:["II também é verdadeira.","I também é verdadeira.","Correta.","III é falsa.","III é falsa."]},
 {id:6,area:"Programação",topic:"Estruturas de Dados",difficulty:"Média",prompt:"Em uma árvore AVL, o fator de balanceamento de cada nó deve permanecer em qual intervalo?",options:["[-2, 2]","[-1, 1]","[0, 1]","Somente 0","Sem restrição"],answer:1,explanation:"A diferença entre alturas deve ser -1, 0 ou 1.",wrong:["Desequilíbrio excessivo.","Correta.","Exclui inclinação à esquerda.","Perfeitamente balanceada.","AVL impõe restrição."]},
 {id:7,area:"Modelagem",topic:"UML 2.x",difficulty:"Fácil",prompt:"Qual diagrama UML representa a troca temporal de mensagens entre objetos?",options:["Classes","Componentes","Sequência","Implantação","Pacotes"],answer:2,explanation:"O diagrama de sequência enfatiza linhas de vida e mensagens no tempo.",wrong:["Estrutura estática.","Componentes.","Correta.","Nós de execução.","Organização."]},
 {id:8,area:"Programação",topic:"Java",difficulty:"Média",prompt:"Em Java, qual recurso permite implementações distintas para métodos com a mesma assinatura herdada?",options:["Sobrecarga","Sobrescrita","Encapsulamento","Agregação","Serialização"],answer:1,explanation:"Sobrescrita redefine na subclasse um método herdado.",wrong:["Varia parâmetros.","Correta.","Protege estado.","Relação entre objetos.","Persiste estado."]}
];
export const flashcards=[["ACID","Atomicidade, Consistência, Isolamento e Durabilidade.","Banco de Dados"],["Busca binária","Complexidade O(log n); exige dados ordenados.","Algoritmos"],["Strategy","Encapsula uma família de algoritmos intercambiáveis.","GoF"],["3FN","2FN + determinante superchave ou dependente atributo primo.","Normalização"],["Sequência","Mensagens entre linhas de vida ao longo do tempo.","UML"],["AVL","BST balanceada com fator entre -1 e 1.","Estruturas"]] as const;
