export type Topic = { id:string; area:string; name:string; weight:number; frequency:number };
export type Question = { id:number; area:string; topic:string; difficulty:string; prompt:string; options:string[]; answer:number; explanation:string; wrong:string[] };
export const exam={date:null as string|null,dateLabel:"Não informado nos arquivos recebidos",totalQuestions:60,distribution:[["Língua Portuguesa",10],["Fundamentos da Educação, transversais e legislação",10],["Tecnologia Aplicada à Educação",10],["Conhecimentos Específicos de Informática",20]] as [string,number][],bibliography:"Não informada nos arquivos recebidos",historicalComparison:"Não disponível: o edital e a prova anterior não foram anexados."};
export const topics:Topic[]=[
 ["alg","Programação","Algoritmos e Lógica de Programação",40,88],["ed","Programação","Estruturas de Dados",40,82],["poo","Programação","Programação Orientada a Objetos",40,79],["es","Engenharia de Software","Definição, processos e gerência de projetos",10,55],
 ["bd1","Banco de Dados","Fundamentos, arquivos e modelo ER",30,80],["bd2","Banco de Dados","Normalização e dependências funcionais",30,92],["bd3","Banco de Dados","Álgebra e cálculo relacional",30,68],["bd4","Banco de Dados","Arquiteturas, modelos lógicos e representação física",30,64],["bd5","Banco de Dados","Organização de arquivos e métodos de acesso",30,61],["bd6","Banco de Dados","DDL, DML, DCL e DTL",30,84],["bd7","Banco de Dados","Apoio à decisão, DW, ETL, OLAP, Data Mining e BI",30,60],["bd8","Banco de Dados","Modelagem, otimização, distribuídos e cluster",30,66],["bd9","Banco de Dados","Segurança, autorização, usuários e perfis",30,62],["bd10","Banco de Dados","Transações, concorrência e recuperação",30,90],["bd11","Banco de Dados","Integridade, backup, restauração e continuidade",30,76],["bd12","Banco de Dados","Processos, documentação e aplicações com BD",30,58],
 ["uml","Modelagem","UML 2.x",20,74],["gof","Modelagem","Padrões de Projeto GoF",20,77],["java","Linguagens","Java",40,84],["python","Linguagens","Python",40,86],["php","Linguagens","PHP",40,62],["port","Língua Portuguesa","Interpretação e gramática aplicada",17,70],["edu","Fundamentos da Educação","Fundamentos, transversais e legislação",17,70],["tec","Tecnologia Educacional","Tecnologia aplicada à educação",17,70]
].map(([id,area,name,weight,frequency])=>({id,area,name,weight,frequency} as Topic));
export const questions:Question[]=[
 {id:1,area:"Programação",topic:"Algoritmos",difficulty:"Média",prompt:"Considere a busca binária em um vetor ordenado com 1.024 elementos distintos. No pior caso, quantas comparações são necessárias para concluir que um valor não está no vetor?",options:["9","10","11","512","1.024"],answer:2,explanation:"Como 1.024 = 2¹⁰, uma busca malsucedida pode exigir 11 comparações para alcançar o intervalo vazio.",wrong:["Desconsidera passos.","Desconsidera a comparação final.","Correta.","Busca linear parcial.","Busca linear completa."]},
 {id:2,area:"Banco de Dados",topic:"Normalização",difficulty:"Média",prompt:"Uma relação está na 3FN quando está na 2FN e, para toda dependência funcional não trivial X → A, qual condição é suficiente?",options:["X não é superchave","A é chave primária","X é superchave ou A é atributo primo","A não admite NULL","X tem um atributo"],answer:2,explanation:"A 3FN admite que X seja superchave ou que A seja atributo primo.",wrong:["É o oposto.","Não exige chave primária.","Correta.","Nullabilidade não define 3FN.","A cardinalidade não é o critério."]},
 {id:3,area:"Programação",topic:"Python",difficulty:"Fácil",prompt:"Qual é a saída de: valores = [1, 2, 3]; print([x*x for x in valores if x % 2])?",options:["[1, 4, 9]","[1, 9]","[2]","[2, 6]","Erro"],answer:1,explanation:"O filtro mantém 1 e 3; a expressão produz 1 e 9.",wrong:["Ignora o filtro.","Correta.","Confunde filtro e resultado.","Não eleva ao quadrado.","A sintaxe é válida."]},
 {id:4,area:"Modelagem",topic:"Padrões GoF",difficulty:"Média",prompt:"Qual padrão define uma família de algoritmos, encapsula cada um e os torna intercambiáveis em tempo de execução?",options:["Observer","Strategy","Facade","Builder","Singleton"],answer:1,explanation:"Strategy encapsula algoritmos atrás de uma interface comum.",wrong:["Notifica dependentes.","Correta.","Simplifica subsistema.","Constrói objetos.","Controla instanciação."]},
 {id:5,area:"Banco de Dados",topic:"Transações",difficulty:"Difícil",prompt:"I. Leitura suja pode ocorrer em READ UNCOMMITTED. II. SERIALIZABLE impede anomalias de serialização. III. Durabilidade garante isolamento. Assinale a correta.",options:["Somente I","Somente II","I e II","II e III","I, II e III"],answer:2,explanation:"I e II são verdadeiras. Durabilidade é permanência após commit, não isolamento.",wrong:["II também é verdadeira.","I também é verdadeira.","Correta.","III é falsa.","III é falsa."]},
 {id:6,area:"Programação",topic:"Estruturas de Dados",difficulty:"Média",prompt:"Em uma árvore AVL, o fator de balanceamento de cada nó deve permanecer em qual intervalo?",options:["[-2, 2]","[-1, 1]","[0, 1]","Somente 0","Sem restrição"],answer:1,explanation:"A diferença entre alturas deve ser -1, 0 ou 1.",wrong:["Desequilíbrio excessivo.","Correta.","Exclui inclinação à esquerda.","Perfeitamente balanceada.","AVL impõe restrição."]},
 {id:7,area:"Modelagem",topic:"UML 2.x",difficulty:"Fácil",prompt:"Qual diagrama UML representa a troca temporal de mensagens entre objetos?",options:["Classes","Componentes","Sequência","Implantação","Pacotes"],answer:2,explanation:"O diagrama de sequência enfatiza linhas de vida e mensagens no tempo.",wrong:["Estrutura estática.","Componentes.","Correta.","Nós de execução.","Organização."]},
 {id:8,area:"Programação",topic:"Java",difficulty:"Média",prompt:"Em Java, qual recurso permite implementações distintas para métodos com a mesma assinatura herdada?",options:["Sobrecarga","Sobrescrita","Encapsulamento","Agregação","Serialização"],answer:1,explanation:"Sobrescrita redefine na subclasse um método herdado.",wrong:["Varia parâmetros.","Correta.","Protege estado.","Relação entre objetos.","Persiste estado."]}
];
export const flashcards=[["ACID","Atomicidade, Consistência, Isolamento e Durabilidade.","Banco de Dados"],["Busca binária","Complexidade O(log n); exige dados ordenados.","Algoritmos"],["Strategy","Encapsula uma família de algoritmos intercambiáveis.","GoF"],["3FN","2FN + determinante superchave ou dependente atributo primo.","Normalização"],["Sequência","Mensagens entre linhas de vida ao longo do tempo.","UML"],["AVL","BST balanceada com fator entre -1 e 1.","Estruturas"]] as const;
