"use client";
import type { Question } from "./data";

export type Attempt = { questionId:number; topic:string; chosen:number; correct:number; isCorrect:boolean; answeredAt:string };
export type StudyRecord = { id:string; date:string; minutes:number };
export type AIMessage = { id:string; role:"user"|"assistant"; content:string; createdAt:string; assistant:string };
export type DailyPlan = { date:string; generatedAt:string; recommendedMinutes:number; questionTarget:number; minutesPerQuestion:number; questionBlockMinutes:number; focusTopics:string[]; rationale:string; generatedByAi:boolean };
export type QuestionReview = { id:string; questionId:number; chosen:number; correct:number; isCorrect:boolean; reviewedAt:string };
export type Progress = {
  answered:number; correct:number; studyMinutes:number; streak:number; favorites:number[];
  topicStatus:Record<string,string>; confidence:Record<string,number>; completedSessions:string[];
  errors:{questionId:number;chosen:number;correct:number;topic:string;reason:string;note:string;nextReview:string;resolved:boolean;prompt?:string;options?:string[]}[];
  reviews:Record<number,string>; simulationHistory:{date:string;score:number;total:number;mode:string}[];
  generatedQuestions:Question[]; attemptHistory:Attempt[]; studyHistory:StudyRecord[]; profile:{name:string};
  aiChats:Record<string,AIMessage[]>;
  dailyPlans:Record<string,DailyPlan>;
  questionReviews:QuestionReview[];
  settings:{dailyGoal:number;hours:number;weekdays:number[];specificPriority:number;examDate:string;weights:{edital:number;frequency:number;errors:number;overdue:number}};
};

export const initial:Progress={answered:0,correct:0,studyMinutes:0,streak:0,favorites:[],topicStatus:{},confidence:{},completedSessions:[],errors:[],reviews:{},simulationHistory:[],generatedQuestions:[],attemptHistory:[],studyHistory:[],aiChats:{},dailyPlans:{},questionReviews:[],profile:{name:""},settings:{dailyGoal:90,hours:1.5,weekdays:[1,2,3,4,5,6],specificPriority:60,examDate:"",weights:{edital:30,frequency:25,errors:25,overdue:20}}};
const KEY="ebtt-ifmt-progress-v2";
let remoteReady=false;
const LOOP_QUESTION_SIGNATURE="Se N = 4, o valor impresso ser\u00e1 4.";
function repairKnownQuestion(q:Question):Question{if(!q.prompt.includes(LOOP_QUESTION_SIGNATURE)||!q.prompt.includes("Se N = 5, o valor impresso ser\u00e1 3."))return q;return{...q,answer:3,explanation:"Conceito: O acumulador soma os valores pares e subtrai 1 para cada valor \u00edmpar. Resolu\u00e7\u00e3o: Para N = 4, S = -1 + 2 - 1 + 4 = 4; para N = 5, S = 3; portanto I, II e III s\u00e3o verdadeiras. Armadilha: O gabarito deve apontar para a alternativa que re\u00fane as tr\u00eas afirma\u00e7\u00f5es.",wrong:["Omite a afirma\u00e7\u00e3o II, que tamb\u00e9m \u00e9 verdadeira.","Omite a afirma\u00e7\u00e3o I, que tamb\u00e9m \u00e9 verdadeira.","Omite a afirma\u00e7\u00e3o III, pois o la\u00e7o executa N vezes e tem complexidade O(N).","Correta: I, II e III s\u00e3o verdadeiras.","I e II tamb\u00e9m s\u00e3o verdadeiras."],sourceNote:"Quest\u00e3o corrigida e revisada por IA; o gabarito correto \u00e9 D."}}
function normalize(old:Partial<Progress>):Progress{const generatedQuestions=(old.generatedQuestions||[]).map(repairKnownQuestion),knownIds=new Set(generatedQuestions.filter(q=>q.prompt.includes(LOOP_QUESTION_SIGNATURE)).map(q=>q.id)),attemptHistory=(old.attemptHistory||[]).map(a=>knownIds.has(a.questionId)?{...a,correct:3,isCorrect:a.chosen===3}:a),errors=(old.errors||[]).map(e=>knownIds.has(e.questionId)?{...e,correct:3,resolved:e.chosen===3}:e);return{...initial,...old,profile:{...initial.profile,...old.profile},settings:{...initial.settings,...old.settings,weights:{...initial.settings.weights,...old.settings?.weights}},generatedQuestions,attemptHistory,errors,answered:attemptHistory.length,correct:attemptHistory.filter(a=>a.isCorrect).length,studyHistory:old.studyHistory||[],aiChats:old.aiChats||{},dailyPlans:old.dailyPlans||{},questionReviews:old.questionReviews||[]}}
function local():Progress{try{return normalize(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("ebtt-ifmt-progress-v1")||"{}"))}catch{return initial}}
function union<T>(a:T[],b:T[],key:(item:T)=>string){const rows=new Map<string,T>();for(const item of [...a,...b])rows.set(key(item),item);return[...rows.values()]}
function mergeQuestions(remote:Question[],device:Question[]){const rows=new Map<number,Question>();for(const item of [...remote,...device]){const saved=rows.get(item.id),savedReviewed=saved?.sourceNote?.includes("revisada por IA"),incomingReviewed=item.sourceNote?.includes("revisada por IA");if(!saved||incomingReviewed||!savedReviewed)rows.set(item.id,item)}return[...rows.values()]}
function merge(remote:Progress,device:Progress):Progress{const attemptHistory=union(remote.attemptHistory,device.attemptHistory,a=>`${a.questionId}:${a.answeredAt}`),studyHistory=union(remote.studyHistory,device.studyHistory,s=>s.id),generatedQuestions=mergeQuestions(remote.generatedQuestions,device.generatedQuestions),errors=union(remote.errors,device.errors,e=>`${e.questionId}:${e.chosen}:${e.nextReview}`),questionReviews=union(remote.questionReviews,device.questionReviews,r=>r.id),chatKeys=new Set([...Object.keys(remote.aiChats),...Object.keys(device.aiChats)]),aiChats=Object.fromEntries([...chatKeys].map(key=>[key,union(remote.aiChats[key]||[],device.aiChats[key]||[],m=>m.id).slice(-40)]));return normalize({...remote,...device,attemptHistory,studyHistory,generatedQuestions,errors,questionReviews,aiChats,dailyPlans:{...remote.dailyPlans,...device.dailyPlans},favorites:[...new Set([...remote.favorites,...device.favorites])],completedSessions:[...new Set([...remote.completedSessions,...device.completedSessions])],topicStatus:{...remote.topicStatus,...device.topicStatus},confidence:{...remote.confidence,...device.confidence},reviews:{...remote.reviews,...device.reviews},simulationHistory:union(remote.simulationHistory,device.simulationHistory,s=>`${s.date}:${s.mode}`),answered:attemptHistory.length,correct:attemptHistory.filter(a=>a.isCorrect).length,studyMinutes:Math.max(remote.studyMinutes,device.studyMinutes,studyHistory.reduce((sum,s)=>sum+s.minutes,0))})}
async function put(progress:Progress){return fetch("/api/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(progress)})}
async function syncFromDatabase(device:Progress){try{const response=await fetch("/api/progress",{cache:"no-store"});if(!response.ok)return;const data=await response.json();if(data.progress){const combined=merge(normalize(data.progress),device);await put(combined);if(JSON.stringify(combined)!==JSON.stringify(device)){localStorage.setItem(KEY,JSON.stringify(combined));location.reload();return}}remoteReady=true;if(!data.progress)await put(device)}catch{/* mantém o modo local quando estiver offline */}}
export function load():Progress{const device=local();void syncFromDatabase(device);return device}
export function save(v:Progress){localStorage.setItem(KEY,JSON.stringify(v));if(remoteReady)void put(v).catch(()=>null)}
export function reset(){localStorage.setItem(KEY,JSON.stringify(initial));remoteReady=false;void fetch("/api/progress",{method:"DELETE"}).catch(()=>null);return initial}
